@extends('layouts.admin')
@section('title', __('Overview'))
@section('crumb', __('Overview'))
@section('content')
<div class="admin-welcome"><div><span class="admin-kicker">{{ __('STUDIO OVERVIEW') }} · {{ now()->locale(app()->getLocale())->translatedFormat('l, F j') }}</span><h1>{{ __('Good to see you') }}, {{ str(auth()->user()->name)->before(' ') }}.</h1><p>{{ __('Here\'s what is happening across your website.') }}</p></div><a class="button button-primary" href="{{ route('admin.content.create', 'posts') }}">＋ {{ __('Write an article') }}</a></div>
<div class="admin-stats">@foreach([['Pages & sections','sections','▦'],['Services','services','◈'],['Projects','projects','▧'],['Articles','posts','▤'],['Team members','team','♙']] as [$label,$type,$icon])<a class="stat-card" href="{{ route('admin.content.index', $type) }}"><span>{{ $icon }}</span><b>{{ $counts[$type] ?? 0 }}</b><small>{{ __($label) }}</small></a>@endforeach</div>
<div class="dashboard-columns"><section class="admin-card"><div class="admin-card-heading"><div><h2>{{ __('Recent messages') }}</h2><p>{{ __('Latest notes from your contact form') }}</p></div><a href="{{ route('admin.content.index', 'messages') }}">{{ __('Open inbox') }} ↗</a></div>@forelse($recentMessages as $message)<div class="message-row"><span class="message-dot {{ $message->read_at ? '' : 'unread' }}"></span><div><b>{{ $message->name }}</b><small>{{ $message->subject }} · {{ $message->created_at->diffForHumans() }}</small></div><a href="{{ route('admin.content.index', 'messages') }}">{{ __('Open') }}</a></div>@empty<div class="admin-empty"><span>✉</span><p>{{ __('Your inbox is quiet for now.') }}</p></div>@endforelse</section>
<section class="admin-card"><div class="admin-card-heading"><div><h2>{{ __('Quick actions') }}</h2><p>{{ __('Jump into a common task') }}</p></div></div><div class="quick-actions"><a href="{{ route('admin.content.create', 'projects') }}"><span>＋</span><b>{{ __('Add a project') }}</b><small>{{ __('Share recent work') }}</small></a><a href="{{ route('admin.content.create', 'services') }}"><span>◈</span><b>{{ __('Update services') }}</b><small>{{ __('Manage capabilities') }}</small></a><a href="{{ route('admin.content.index', 'sections') }}"><span>▦</span><b>{{ __('Edit homepage') }}</b><small>{{ __('Adjust your story') }}</small></a><a href="{{ route('admin.content.index', 'settings') }}"><span>⚙</span><b>{{ __('Site settings') }}</b><small>{{ __('Brand and contact info') }}</small></a><a href="{{ route('admin.footer-settings.edit') }}"><span>✉</span><b>{{ __('Footer settings') }}</b><small>{{ __('Update public footer content') }}</small></a></div><div class="inbox-summary"><span>{{ __('Unread messages') }}</span><b>{{ $unreadMessages }}</b></div></section></div>
@endsection
