@extends('layouts.admin')
@section('title', ($record ? 'Edit ' : 'Add ').str($config['label'])->singular())
@section('crumb', $config['label'])
@section('content')
<div class="admin-page-heading"><div><span class="admin-kicker"><a href="{{ route('admin.content.index', $type) }}">{{ $config['label'] }}</a> / {{ $record ? 'EDIT' : 'NEW' }}</span><h1>{{ $record ? 'Edit item' : 'Create item' }}</h1><p>Update the details for this item. Published changes are visible on the website right away.</p></div><a class="text-link" href="{{ route('admin.content.index', $type) }}">← Back to {{ $config['label'] }}</a></div><form class="cms-form" method="post" enctype="multipart/form-data" action="{{ $record ? route('admin.content.update', [$type, $record->id]) : route('admin.content.store', $type) }}">@csrf @if($record) @method('PUT') @endif<div class="cms-form-grid"><section class="admin-card cms-fields"><div class="admin-card-heading"><div><h2>Content details</h2><p>Fields marked as required must be filled in.</p></div></div><div class="form-grid">@foreach($config['fields'] as $name=>$kind)@php $value = old($name, $record?->{$name}); @endphp<label class="cms-field {{ in_array($kind, ['textarea','richtext','list','image'], true) ? 'wide-field' : '' }}"><span>{{ str($name)->replace('_', ' ')->title() }}@if(in_array($name, ['title','name','person_name','quote','key'], true)) <b>*</b>@endif</span>
@if($kind==='textarea' || $kind==='richtext')<textarea name="{{ $name }}" rows="{{ $kind==='richtext' ? 12 : 4 }}">{{ $value }}</textarea>
@elseif($kind==='list')<textarea name="{{ $name }}" rows="5" placeholder="One item per line">{{ is_array($value) ? implode("\n", $value) : $value }}</textarea><small>Enter one item per line.</small>
@elseif($kind==='links')<textarea name="{{ $name }}" rows="5" placeholder="LinkedIn|https://...">{{ is_array($value) ? collect($value)->map(fn ($url, $label) => $label.'|'.$url)->implode("\n") : $value }}</textarea><small>One link per line in label|URL format. Only HTTP and HTTPS links are saved.</small>
@elseif($kind==='boolean')<span class="toggle-field"><input type="checkbox" name="{{ $name }}" value="1" @checked(old($name, $record?->{$name} ?? false))><span>{{ str($name)->replace('_', ' ')->title() }}</span></span>
@elseif($kind==='image')@if($value)<img class="image-preview" src="{{ Storage::disk('public')->url($value) }}" alt="Current image">@endif<input type="file" name="{{ $name }}" accept="image/jpeg,image/png,image/webp,image/gif"><small>JPG, PNG, WebP or GIF. Up to 5 MB.</small>
@elseif($kind==='setting_value' && in_array(old('key', $record?->key), ['logo_path','favicon_path'], true))@if($value)<img class="image-preview" src="{{ Storage::disk('public')->url($value) }}" alt="Current brand asset">@endif<input type="file" name="{{ $name }}" accept="image/jpeg,image/png,image/webp,image/gif"><small>Upload a JPG, PNG, WebP or GIF up to 5 MB.</small>
@elseif($kind==='setting_value')<textarea name="{{ $name }}" rows="4">{{ $value }}</textarea>
@elseif($kind==='project_category' || $kind==='blog_category')<select name="{{ $name }}"><option value="">No category</option>@foreach(($kind==='project_category' ? \App\Models\ProjectCategory::query()->orderBy('name')->get() : \App\Models\BlogCategory::query()->orderBy('name')->get()) as $option)<option value="{{ $option->id }}" @selected($value==$option->id)>{{ $option->name }}</option>@endforeach</select>
@elseif($kind==='technology_list')<select name="technologies[]" multiple size="5">@foreach(\App\Models\Technology::query()->orderBy('name')->get() as $option)<option value="{{ $option->id }}" @selected($record?->technologies?->contains('id', $option->id))>{{ $option->name }}</option>@endforeach</select><small>Hold Ctrl or Command to select multiple.</small>
@elseif($kind==='date' || $kind==='datetime')<input type="{{ $kind==='date' ? 'date' : 'datetime-local' }}" name="{{ $name }}" value="{{ $value ? \Illuminate\Support\Carbon::parse($value)->format($kind==='date' ? 'Y-m-d' : 'Y-m-d\TH:i') : '' }}">
@elseif($kind==='number')<input type="number" min="0" name="{{ $name }}" value="{{ $value ?? 0 }}">
@else<input type="{{ $kind==='url' ? 'url' : 'text' }}" name="{{ $name }}" value="{{ $value }}" @readonly(in_array($name, ['key'], true) && $record) @readonly($type==='pages' && $name==='slug')>
@endif @error($name)<small class="field-error">{{ $message }}</small>@enderror</label>@endforeach</div></section><aside class="admin-card publish-card"><h2>Publishing</h2><p>Save your changes when you are ready.</p><div class="publish-state"><span class="publish-dot"></span>{{ $record ? 'Saved content' : 'New content' }}</div><button class="button button-primary" type="submit">{{ $record ? 'Save changes' : 'Create item' }} <span>↗</span></button><a class="cancel-link" href="{{ route('admin.content.index', $type) }}">Cancel</a></aside></div></form>
@endsection
